KurumsalWeb/Models/Entity/Slider.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderID { get; set; }
        public string SliderBaslik { get; set; }
        public string SliderAciklama { get; set; }
    }
}

KurumsalWeb/Controllers/SliderController.cs
using KurumsalWeb.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KurumsalWeb.Controllers
{
    public class SliderController : Controller
    {
        // GET: Slider
        KurumsalWebDbEntities db = new KurumsalWebDbEntities();
        public ActionResult Index()
        {
            return View(db.Slider.ToList());
        }
        public ActionResult YeniSlider()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult YeniSlider(Slider s)
        {
            db.Slider.Add(s);
            db.SaveChanges();
            return RedirectToAction("/Index");
        }

        public ActionResult SliderSil(int id)
        {
            var sil = db.Slider.Where(x => x.SliderID == id).SingleOrDefault();
            db.Slider.Remove(sil);
            db.SaveChanges();
            return RedirectToAction("/Index");
        }

        public ActionResult SliderGuncelle(int id)
        {
            var sg = db.Slider.Find(id);
            return View("SliderGuncelle", sg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SliderGuncelle(int id,Slider slider)
        {
            var sg = db.Slider.Where(x => x.SliderID == id).SingleOrDefault();
            sg.SliderBaslik = slider.SliderBaslik;
            sg.SliderAciklama = slider.SliderAciklama;
            db.SaveChanges();
            return RedirectToAction("/Index");
        }
    }
}

KurumsalWeb/Views/Slider/Index.cshtml
@model IEnumerable<KurumsalWeb.Models.Entity.Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 style="margin-bottom:20px;" align="center">Slider Listesi</h1>
@*<a href="/Slider/YeniSlider" class="btn btn-outline-primary " style="max-width:12%; margin-bottom:25px;">Yeni Slider Ekle</a>*@


    <button style="max-width:12%; margin-bottom:25px;" type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#Modal1">
         Yeni Slider
    </button>


<!-- The Modal -->
    <div class="modal" id="Modal1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Yeni Slider Oluştur</h2>
                </div>
                <form method="post" action="/Slider/YeniSlider">
                    <div class="modal-body">
                        <label> Başlık</label>
                        <input type="text" name="SliderBaslik" required placeholder="Slider Başlığı Giriniz" class="form-control">
                        <br />
                        <label> Açıklama</label>
                        <textarea name="SliderAciklama" class="ckeditor" ></textarea>
                        <br />
                        <button type="submit" class="btn btn-success">Kaydet</button>
                        <button  type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- Table with hoverable rows -->
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Başlık</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var slider in Model)
        {
            <tr>
                <th>@slider.SliderID</th>
                <td>@slider.SliderBaslik</td>
                <td>@Html.Raw(slider.SliderAciklama)</td>

                <td><a href="/Slider/SliderSil/@slider.SliderID" class="btn btn-danger">Sil</a></td>
                <td><a href="/Slider/SliderGuncelle/@slider.SliderID" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }

    </tbody>
</table>

KurumsalWeb/Views/Slider/SliderGuncelle.cshtml
@model KurumsalWeb.Models.Entity.Slider
@{
    ViewBag.Title = "SliderGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 style="margin-bottom:20px;" align="center">Slider Güncelle</h1>
<hr />
<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>

@using (Html.BeginForm("SliderGuncelle", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Başlık</label>
        <div class="col-sm-8">
            <input type="text" name="SliderBaslik" value="@Model.SliderBaslik" class="form-control">
        </div>
    </div>
    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Açıklama</label>
        <div class="col-sm-8">
            <textarea name="SliderAciklama" required class="ckeditor">@Model.SliderAciklama</textarea>
        </div>
    </div>


    <button type="submit" class="btn btn-success">Güncelle</button>
}

KurumsalWeb/Views/Slider/YeniSlider.cshtml
@{
    ViewBag.Title = "YeniSlider";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 style="margin-bottom:20px;" align="center">Yeni Blog</h1>
<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>
@using (Html.BeginForm("YeniSlider", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <!-- General Form Elements -->

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Başlık</label>
        <div class="col-sm-9">
            <input type="text" name="SliderBaslik" required placeholder="Slider Başlığı Giriniz" class="form-control">
        </div>
    </div>


    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Açıklama</label>
        <div class="col-sm-9">
            <textarea  name="SliderAciklama" class="ckeditor"></textarea>
        </div>
    </div>

  

    <button style="margin-top:25px; width:100px;" type="submit" class="btn btn-success ">Ekle</button>
}