KurumsalWeb/Models/Entity/Kimlik.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kimlik
    {
        public int KimlikID { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string LogoUrl { get; set; }
        public string Unvan { get; set; }
    }
}

KurumsalWeb/Controllers/KimlikController.cs
using KurumsalWeb.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace KurumsalWeb.Controllers
{
   
    public class KimlikController : Controller
    {
        KurumsalWebDbEntities db = new KurumsalWebDbEntities();
        // GET: Kimlik
        public ActionResult Index()
        {
            return View(db.Kimlik.ToList());
        }

        // GET: Kimlik/Edit/5
        public ActionResult Edit(int id)
        {
            var kimlik = db.Kimlik.Where(x => x.KimlikID == id).SingleOrDefault();
            return View(kimlik);
        }

        // POST: Kimlik/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(int id, Kimlik kimlik,HttpPostedFileBase LogoUrl)
        {
            if (ModelState.IsValid)
            {
                var k = db.Kimlik.Where(x => x.KimlikID == id).SingleOrDefault();
                if (LogoUrl !=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(k.LogoUrl)))
                    {
                        System.IO.File.Delete(Server.MapPath(k.LogoUrl));
                    }
                    WebImage img = new WebImage(LogoUrl.InputStream);
                    FileInfo imgInfo = new FileInfo(LogoUrl.FileName);

                    string logoName =LogoUrl.FileName + imgInfo.Extension;
                    img.Resize(100, 100);
                    img.Save("~/Uploads/Kimlik/" + logoName);
                    k.LogoUrl = "/Uploads/Kimlik/" + logoName;
                }
                k.Title = kimlik.Title;
                k.Keywords = kimlik.Keywords;
                k.Description = kimlik.Description;
                k.Unvan = kimlik.Unvan;
                db.SaveChanges();
                return RedirectToAction("/Index");
            }
            return View(kimlik);
        }


    }
}

KurumsalWeb/Views/Kimlik/Edit.cshtml
@model KurumsalWeb.Models.Entity.Kimlik
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1 style="margin-bottom:20px;" align="center">Site Ayarları Güncelle</h1>
<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>

@using (Html.BeginForm("Edit","Kimlik",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Site Başlığı</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(x=>x.Title, new { @class = "form-control" })
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Site Anahtar Kelimeler</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(x => x.Keywords, new { @class = "form-control" })
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Site Açıklama</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputNumber" class="col-sm-2 col-form-label">Logo</label>
        <div class="col-sm-9">
            <input class="form-control" type="file" name="LogoUrl" accept=".png,.jpg,.jpeg" id="formFile">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Ünvan</label>
        <div class="col-sm-9">
            @Html.TextBoxFor(x => x.Unvan, new { @class = "form-control" })
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Güncelle</button>
}

KurumsalWeb/Views/Kimlik/Index.cshtml
@using KurumsalWeb.Models.Entity
@model List<Kimlik>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1 style="margin-bottom:30px; margin-top:10px;" align="center">Site Ayar Sayfası</h1>
<br />
<br />
<!-- Table with hoverable rows -->
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Site Başlık</th>
            <th scope="col">Anahtar Kelimeler</th>
            <th scope="col">Site Açıklama</th>
            <th scope="col">Site Logo</th>
            <th scope="col">Site Ünvan</th>
            <th scope="col">Düzenle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kimlik in Model)
        {
        <tr>
            <th>@kimlik.KimlikID</th>
            <td>@kimlik.Title</td>
            <td>@kimlik.Keywords</td>
            <td>@Html.Raw(kimlik.Description)</td>
            <td><img src="@kimlik.LogoUrl" /></td>
            <td>@kimlik.Unvan</td>
            <td><a href="/Kimlik/Edit/@kimlik.KimlikID" class="btn btn-warning">Güncelle</a></td>
        </tr>
        }

    </tbody>
</table>
<!-- End Table with hoverable rows -->