KurumsalWeb/Models/Entity/Hizmet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmet
    {
        public int HizmetID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string ResimUrl { get; set; }
    }
}

KurumsalWeb/Controllers/HizmetController.cs
using KurumsalWeb.Models.Entity;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace KurumsalWeb.Controllers
{
    public class HizmetController : Controller
    {
        // GET: Hizmet
        KurumsalWebDbEntities db = new KurumsalWebDbEntities();
        public ActionResult Index()
        {
            return View(db.Hizmet.ToList());
        }
        [HttpGet]
        public ActionResult YeniHizmet()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult YeniHizmet(Hizmet h , HttpPostedFileBase ResimUrl)
        {
            if (ModelState.IsValid)
            {
                if (ResimUrl!=null)
                {
                    WebImage img = new WebImage(ResimUrl.InputStream);
                    FileInfo imgInfo = new FileInfo(ResimUrl.FileName);

                    string logoName = Guid.NewGuid().ToString() + imgInfo.Extension;
           
                    img.Save("~/Uploads/Hizmet/" + logoName);
                    h.ResimUrl = "/Uploads/Hizmet/" + logoName;
                }
                db.Hizmet.Add(h);
                db.SaveChanges();
                return RedirectToAction("/Index");
              
            }
            return View(h);
        }

        public ActionResult HizmetSil(int id)
        {
            var hizmetSil = db.Hizmet.Where(x => x.HizmetID == id).FirstOrDefault();
            db.Hizmet.Remove(hizmetSil);
            db.SaveChanges();
            return RedirectToAction("/Index");
        }

        public ActionResult HizmetEdit(int id)
        {
            var hizmetGetir = db.Hizmet.Find(id);
            return View("HizmetEdit", hizmetGetir);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult HizmetEdit(int? id, Hizmet hizmet,HttpPostedFileBase ResimUrl)
        {
            if (ModelState.IsValid)
            {
                var h = db.Hizmet.Where(x => x.HizmetID == id).SingleOrDefault();
                if (ResimUrl!=null)
                {
                    if (System.IO.File.Exists(Server.MapPath(h.ResimUrl)))
                    {
                        System.IO.File.Delete(Server.MapPath(h.ResimUrl));
                    }
                    WebImage img = new WebImage(ResimUrl.InputStream);
                    FileInfo imgInfo = new FileInfo(ResimUrl.FileName);

                    string HizmetImage = Guid.NewGuid().ToString() + imgInfo.Extension;
           
                    img.Save("~/Uploads/Hizmet/" + HizmetImage);
                    h.ResimUrl = "/Uploads/Hizmet/" + HizmetImage;
                }
                h.Baslik = hizmet.Baslik;
                h.Aciklama = hizmet.Aciklama;
                db.SaveChanges();
                return RedirectToAction("/Index");
            }
            return View();
        }
    }
}

KurumsalWeb/Views/Hizmet/HizmetEdit.cshtml
@model KurumsalWeb.Models.Entity.Hizmet
@{
    ViewBag.Title = "HizmetEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 style="margin-bottom:20px;" align="center">Hizmet Güncelle</h1>
<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>
@using (Html.BeginForm("HizmetEdit", "Hizmet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <!-- General Form Elements -->

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Başlık</label>
        <div class="col-sm-10">
            <input type="text" name="Baslik" value="@Model.Baslik" class="form-control">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Açıklama</label>
        <div class="col-sm-10">
            <textarea name="Aciklama" class="ckeditor">@Model.Aciklama</textarea>
        </div>
    </div>



    <div class="row mb-3">
        <label for="inputNumber" class="col-sm-2 col-form-label">Önceki Resim</label>
        <div class="col-sm-10">
            @if (Model.ResimUrl == null)
            {
                <img style="width:250px;height:150px;" src="https://haber.webdeogren.com/wp-content/uploads/2020/01/resim-yok.png" />
            }
            <img style="width:250px;height:150px;" src="@Model.ResimUrl" />
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputNumber" class="col-sm-2 col-form-label">Resim</label>
        <div class="col-sm-10">
            <input class="form-control" type="file" name="ResimUrl" accept=".png,.jpg,.jpeg" id="formFile">
        </div>
    </div>

    <button style="margin-top:25px; width:100px;" type="submit" class="btn btn-success ">Ekle</button>
}

KurumsalWeb/Views/Hizmet/Index.cshtml
@using KurumsalWeb.Models.Entity
@model List<Hizmet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1 style="margin-bottom:20px;" align="center">Hizmetlerimiz Sayfası</h1>
<a href="/Hizmet/YeniHizmet" class="btn btn-outline-primary " style="max-width:12%; margin-bottom:25px;">Yeni Hizmet Ekle</a>

<!-- Table with stripped rows -->
<table class="table table-striped" id="tbl">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Başlık</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Resim</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hizmet in Model)
        {
        <tr>
            <th>@hizmet.HizmetID</th>
            <td>@hizmet.Baslik</td>
            <td>@Html.Raw(hizmet.Aciklama)</td>
            <td>
                @if (hizmet.ResimUrl == null)
                {
                    <img style="width:150px;height:100px;" src="https://haber.webdeogren.com/wp-content/uploads/2020/01/resim-yok.png" />

                }

                @if (hizmet.ResimUrl != null)
                {
                    <img style="width:150px;height:100px;" src="@hizmet.ResimUrl" />
                }



            </td>


            <td><a class="btn btn-danger btnSil" data-id="@hizmet.HizmetID">Sil</a></td>
            <td><a href="/Hizmet/HizmetEdit/@hizmet.HizmetID" class="btn btn-warning">Güncelle</a></td>
        </tr>
        }



    </tbody>
</table>
<!-- End Table with stripped rows -->

KurumsalWeb/Views/Hizmet/YeniHizmet.cshtml
@{
    ViewBag.Title = "YeniHizmet";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1 style="margin-bottom:20px;" align="center">Yeni Hizmet</h1>
<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>
@using (Html.BeginForm("YeniHizmet", "Hizmet", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <!-- General Form Elements -->

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Başlık</label>
        <div class="col-sm-10">
            <input type="text" name="Baslik" class="form-control">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputText" class="col-sm-2 col-form-label">Açıklama</label>
        <div class="col-sm-10">
            <textarea name="Aciklama" class="ckeditor"></textarea>
        </div>
    </div>
   
    <div class="row mb-3">
        <label for="inputNumber" class="col-sm-2 col-form-label">Resim</label>
        <div class="col-sm-10">
            <input class="form-control" type="file" name="ResimUrl" accept=".png,.jpg,.jpeg" id="formFile">
        </div>
    </div>

    <button  style="margin-top:25px; width:100px;" type="submit" class="btn btn-success ">Ekle</button>
}